# Generated by Django 5.1.4 on 2025-02-04 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='project',
        ),
        migrations.AddField(
            model_name='file',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
